export const USER_TOKEN_LOADING = 'USER_TOKEN_LOADING';
export const USER_TOKEN_SUCCESS = 'USER_TOKEN_SUCCESS';
export const USER_TOKEN_ERROR = 'USER_TOKEN_ERROR';

export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_EDIT_LOADING = 'USER_EDIT_LOADING';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_ERROR = 'USER_EDIT_ERROR';

export const USER_SIGNUP_LOADING = 'USER_SIGNUP_LOADING';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';
